name: Build Android APK

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        run: |
          git clone --depth 1 "https://github.com/${{ github.repository }}.git" .
          git checkout "${{ github.sha }}"

      - name: Build Android APK
        run: |
          touch .env
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          chmod +x ./gradlew || true
          ./gradlew assembleDebug --no-daemon

      - name: Upload Debug APK
        run: |
          mkdir -p artifacts
          cp app/build/outputs/apk/debug/*.apk artifacts/ || true
          echo "APK build complete!"

      - name: Save APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
